name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      #Ambiente node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      
      #Instalar as dependências NPM/Yarn    
      - name: Install dependencies
        run: yarn
      
      #Copiar projeto para Digital Ocean.
      - name: Copy project to Digital
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SHH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/softwrap-backend"
             
      #Instalar dependencias e dar restart com o pm2
      - name: Ruan productions scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SHH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            cd ~/app/softwrap-backend
            yarn
            pm2 restart softwrap-api 
            
    


